<a href="https://colab.research.google.com/github/KiranJ9/Image-Classification/blob/main/Image_Classification(Proj).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Image Data
!pip install bing-image-downloader

In [6]:
!pip install ipython-autotime
%load_ext autotime

time: 195 µs (started: 2021-04-15 09:04:16 +00:00)


In [3]:
from bing_image_downloader import downloader
downloader.download("burgers",limit = 40,output_dir = 'ImageData')



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://www.k9ofmine.com/wp-content/uploads/2014/09/doggie-burger.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://image.zmenu.com/menupic/191182/s_20181117161012794558.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://image.zmenu.com/menupic/2412137/s_20191211040311261026.jpeg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.netherlands-tourism.com/wp-content/uploads/2013/11/Keukenhof-Tulips-and-Colors.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://deerfootinn.com/wp-content/uploads/2017/04/Kids-Pool-Party-5WEB-1.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://image.zmenu.com/menupic/2352105/s_20190110045251949408.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://image.zmenu.com/menupic/2095631/s_20190725034119443025.jpeg
[%] File Downloaded !

[%] Downloading Image #8 from https://live.staticflickr.com

In [4]:
downloader.download("pizza",limit = 40,output_dir = 'ImageData')



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://klyker.com/wp-content/uploads/2015/03/animals-eating-pizza-20.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://image.zmenu.com/menupic/455322/s_20200204232409179077.jpeg
[%] File Downloaded !

[%] Downloading Image #3 from https://image.zmenu.com/menupic/5036939/s_581df05c-d114-457f-8fa5-56c299d474d1.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.showbizpizza.com/photos/misc/emo/09.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://image.zmenu.com/menupic/208446/s_3907c11c-6ee7-4365-b1d0-aa6908ce4069.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.thestonebakeovencompany.co.uk/wp/wp-content/uploads/Picture1.png
[%] File Downloaded !

[%] Downloading Image #7 from https://image.zmenu.com/menupic/4773095/s_ff931230-b30c-4c64-9557-ec6ed5372420.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://www.winingandd

In [5]:
downloader.download("tasty pastas",limit = 40,output_dir = 'ImageData')



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://img.buzzfeed.com/buzzfeed-static/static/2014-11/30/10/campaign_images/webdr08/easy-pasta-recipes-2-1878-1417359867-9_dblbig.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.liveeatlearn.com/wp-content/uploads/2015/09/pesto-spaghetti-squash-vert.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://irepo.primecp.com/2016/07/290611/Fathers-Day-Menu_ExtraLarge1000_ID-1768226.png?v=1768226
[%] File Downloaded !

[%] Downloading Image #4 from https://i2.wp.com/wellplated.com/wp-content/uploads/2018/07/Grilled-Portobello-Mushrooms.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://marinmamacooks.com/wp-content/uploads/2013/07/chopped-shallots.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://irepo.primecp.com/2015/07/230558/Firecracker-Shrimp_ExtraLarge1000_ID-1117205.jpg?v=1117205
[%] File Downloaded !

[%] Downloading Image #7 from http

In [18]:
#Preprocessing the ImageData
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread #To read the image
from skimage.transform import resize #Resizing the image

DATADIR = '/content/ImageData'
CATEGORIES = ['burgers','pizza','tasty pastas']
for category in CATEGORIES:
  num_class = CATEGORIES.index(category)
  print(num_class)
  path = os.path.join(DATADIR,category)
  print(path)
  for img in os.listdir(path):
    img_read = imread(os.path.join(path,img))
    print(img_read)

Streaming output truncated to the last 5000 lines.
  ...
  [38 65 94]
  [38 65 94]
  [38 65 94]]

 [[17 46 78]
  [18 47 79]
  [18 47 79]
  ...
  [39 66 95]
  [39 66 95]
  [39 66 95]]

 [[19 48 80]
  [19 48 80]
  [20 49 81]
  ...
  [40 67 96]
  [40 67 96]
  [40 67 96]]

 ...

 [[24 22 27]
  [30 28 33]
  [44 42 47]
  ...
  [ 3  5  4]
  [ 4  6  5]
  [ 5  7  6]]

 [[32 29 36]
  [35 32 39]
  [46 43 50]
  ...
  [ 4  6  5]
  [ 5  7  6]
  [ 7  9  8]]

 [[36 33 40]
  [34 31 38]
  [39 36 43]
  ...
  [ 5  7  6]
  [ 7  9  8]
  [ 8 10  9]]]
[[[159  40  46]
  [158  34  44]
  [166  31  48]
  ...
  [ 56  30  31]
  [ 11   0   0]
  [  4   0   0]]

 [[156  35  42]
  [158  32  43]
  [168  33  50]
  ...
  [ 50  24  25]
  [ 11   0   0]
  [  4   0   0]]

 [[155  31  39]
  [161  34  45]
  [174  37  55]
  ...
  [ 47  21  22]
  [ 11   0   0]
  [  4   0   0]]

 ...

 [[194 137 182]
  [190 133 178]
  [186 127 175]
  ...
  [ 76  39  20]
  [ 15   0   0]
  [  2   2   0]]

 [[126  65 109]
  [124  63 107]
  [122  59 1